# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orchestrator_pb2 as orchestrator__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeRegistryStub:
    """Node Registry Service
    Used for node registration and attestation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/orchestrator.NodeRegistry/RegisterNode',
                request_serializer=orchestrator__pb2.NodeRegistrationRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.NodeRegistrationResponse.FromString,
                _registered_method=True)


class NodeRegistryServicer:
    """Node Registry Service
    Used for node registration and attestation.
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=orchestrator__pb2.NodeRegistrationRequest.FromString,
                    response_serializer=orchestrator__pb2.NodeRegistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.NodeRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.NodeRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeRegistry:
    """Node Registry Service
    Used for node registration and attestation.
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.NodeRegistry/RegisterNode',
            orchestrator__pb2.NodeRegistrationRequest.SerializeToString,
            orchestrator__pb2.NodeRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TelemetryStub:
    """Telemetry Service
    Streams telemetry from Node Agents to the Control Plane.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/orchestrator.Telemetry/StreamTelemetry',
                request_serializer=orchestrator__pb2.TelemetrySnapshot.SerializeToString,
                response_deserializer=orchestrator__pb2.TelemetryAck.FromString,
                _registered_method=True)


class TelemetryServicer:
    """Telemetry Service
    Streams telemetry from Node Agents to the Control Plane.
    """

    def StreamTelemetry(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=orchestrator__pb2.TelemetrySnapshot.FromString,
                    response_serializer=orchestrator__pb2.TelemetryAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.Telemetry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.Telemetry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Telemetry:
    """Telemetry Service
    Streams telemetry from Node Agents to the Control Plane.
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/orchestrator.Telemetry/StreamTelemetry',
            orchestrator__pb2.TelemetrySnapshot.SerializeToString,
            orchestrator__pb2.TelemetryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExecutionStub:
    """Execution Service
    Used by the Scheduler to dispatch inference tasks to Node Agents.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/orchestrator.Execution/ExecuteTask',
                request_serializer=orchestrator__pb2.ExecutionRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ExecutionResponse.FromString,
                _registered_method=True)


class ExecutionServicer:
    """Execution Service
    Used by the Scheduler to dispatch inference tasks to Node Agents.
    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=orchestrator__pb2.ExecutionRequest.FromString,
                    response_serializer=orchestrator__pb2.ExecutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.Execution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.Execution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Execution:
    """Execution Service
    Used by the Scheduler to dispatch inference tasks to Node Agents.
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.Execution/ExecuteTask',
            orchestrator__pb2.ExecutionRequest.SerializeToString,
            orchestrator__pb2.ExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
